-- 코드를 입력하세요
SELECT R.CAR_ID, R.CAR_TYPE, R.FEE
FROM (SELECT C.CAR_ID, C.CAR_TYPE, TRUNCATE(C.DAILY_FEE * ((1 - DISCOUNT_RATE / 100)) * 30, 0) FEE
      FROM (SELECT *
            FROM CAR_RENTAL_COMPANY_CAR
            WHERE CAR_TYPE IN ('세단', 'SUV')
            AND CAR_ID NOT IN (SELECT DISTINCT CAR_ID
                               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
                               WHERE H.END_DATE > '2022-11-01' AND H.START_DATE <= '2022-11-30')) C
      JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
      WHERE P.DURATION_TYPE LIKE '30일 이상') R
WHERE R.FEE >= 500000 AND R.FEE < 2000000;

# SELECT DISTINCT CAR_ID 
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
# WHERE H.END_DATE >= '2022-11-01' AND H.START_DATE <= '2022-11-30';

# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
# WHERE H.END_DATE > '2022-11-01' AND H.START_DATE <= '2022-11-30';

# SELECT V.CAR_ID, V.CAR_TYPE, TRUNCATE(V.DAILY_FEE * 30 * DISCOUNT_RATE / 100, 0) FEE, V.START_DATE, V.END_DATE, V.DURATION_TYPE, V.DISCOUNT_RATE
# FROM (SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, H.START_DATE, H.END_DATE, P.DURATION_TYPE, P.DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_CAR C
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE) V
# WHERE V.CAR_TYPE IN ('세단', 'SUV')
# AND (V.END_DATE < '2022-11-01' OR V.START_DATE > '2022-11-30')
# AND V.DURATION_TYPE LIKE '30일 이상';
# AND TRUNCATE(V.DAILY_FEE * 30 * DISCOUNT_RATE / 100, 0) >= 500000 AND TRUNCATE(V.DAILY_FEE * 30 * DISCOUNT_RATE / 100, 0) < 2000000;