-- 코드를 입력하세요
SELECT CH.HISTORY_ID, TRUNCATE(CH.DAILY_FEE * (1 - (IFNULL(P.DISCOUNT_RATE, 0) / 100)) * CH.RENTAL_DATE, 0) FEE
FROM (SELECT C.CAR_TYPE, C.DAILY_FEE, H.HISTORY_ID, DATEDIFF(H.END_DATE, H.START_DATE) + 1 RENTAL_DATE
      FROM CAR_RENTAL_COMPANY_CAR C
      JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
      WHERE C.CAR_TYPE LIKE '트럭') CH
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON CH.CAR_TYPE = P.CAR_TYPE
AND P.DURATION_TYPE LIKE CASE WHEN CH.RENTAL_DATE >= 90 THEN '90일 이상' WHEN CH.RENTAL_DATE >= 30 THEN '30일 이상' WHEN CH.RENTAL_DATE >= 7 THEN '7일 이상' ELSE NULL END
ORDER BY FEE DESC, HISTORY_ID DESC;